---
title: "Portfolio Management Analytics - Individual Gift Officer Report"
author: "Michael Pawlus"
date: "Tuesday, February 23, 2016"
output:
  word_document:
    fig_width: 5
    fig_height: 5
    fig_caption: true
---

```{r, echo=FALSE}
library(ggplot2)
library(RColorBrewer)
library(data.table)
library(plyr)
```



```{r, echo=FALSE}
setwd("C:/Users/pawlusm/Desktop")
act2 <- read.csv("action_eval3.csv", stringsAsFactors = FALSE)
x <- "Smith"   ## set to gift officer last name
act2 <- act2[act2$goLast==x,]
```


This report contains an action report for Gift Officer `r x`

The plot below shows the distribution of actions by real estate tier.

0 - means that we do not have real estate data
1 - real estate values between $1 - $99,999
2 - real estate values between $100,000 - $199,999
... and so on ...
11 - real estate values over $1m

```{r, echo=FALSE, results='asis'}
## convert all missing values to zero
act2[is.na(act2)]   <- 0

## put real estate values into $100,000 buckets
act2$re_grp <- cut(act2$RE_Val, breaks = seq(-1, 999999, by = 100000), label=FALSE)

## code the outliers (all zeroes are coded as zeroes and those over $1M are coded as 11)
act2$re_grp[act2$RE_Val==0] <- 0
act2$re_grp[is.na(act2$re_grp)]   <- 11

## convert rating to factor and then reorder factor levels
act2$re_grp <- as.factor(as.character(act2$re_grp))
act2<- within(act2, re_grp <- reorder(re_grp, as.numeric(as.character(re_grp))))

## plot results (faceted bar plot)
ggplot(data=act2) +
  geom_bar(mapping=aes(x=re_grp, fill=category), binwidth=1) + 
  theme_bw() + 
  scale_color_brewer() +
  labs(title="Actions by Real Estate Value Tiers")
```